AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/console

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: compact

Style/MethodMissing:
  Exclude:
    - lib/pdc/resource/per_thread_registry.rb 

Metrics/LineLength:
  Max: 100
  Exclude:
    - spec/**/*.rb
    - examples/**/*.rb

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25
  Exclude:
    - lib/pdc/config.rb

Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/pdc/**/*.rb
    - examples/**/*.rb

Naming/PredicateName:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - lib/pdc/config.rb
        
